apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: ecserver
  name: ecserver
spec: 
  type: NodePort
  selector: 
    app: ecserver
  ports:
  - name: ecserver
    port: 8081
    targetPort: 8081
    nodePort: 30081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecserver
  template:
    metadata:
      labels:
        app: ecserver
    spec:
      containers:
      - name: ecserver
        image: zbio/ecserver:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: ballot
  name: ballot
spec: 
  type: NodePort
  selector: 
    app: ballot
  ports:
  - name: ballot
    port: 8080
    targetPort: 8080
    nodePort: 30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ballot
  template:
    metadata:
      labels:
        app: ballot
    spec:
      containers:
      - name: ballot
        image: zbio/ballot:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: voter
    type: "roost-example"
  name: voter
spec: 
  type: NodePort
  selector: 
    app: voter
    type: "roost-example"
  ports:
  - name: voter
    port: 80
    targetPort: 80
    nodePort: 30030

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voter
      type: "roost-example"
  template:
    metadata:
      labels:
        app: voter
        type: "roost-example"
    spec:
      containers:
      - name: voter
        image: zbio/voter:latest
        stdin: true
        tty: true
        env:
        - name: REACT_APP_BALLOT_ENDPOINT
          value: roost-controlplane:30080
        - name: REACT_APP_EC_SERVER_ENDPOINT
          value: roost-controlplane:30081
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: sample-test-suite
  name: sample-test-suite
spec: 
  type: NodePort
  selector: 
    app: sample-test-suite
  ports:
  - name: sample-test-suite
    port: 80
    targetPort: 5003
    nodePort: 30088

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballot-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-test-suite
  template:
    metadata:
      labels:
        app: sample-test-suite
    spec:
      containers:
      - name: ballot
        image: zbio/service-test-suite:latest
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: election-commission
    type: "roost-example"
  name: election-commission
spec: 
  type: NodePort
  selector: 
    app: election-commission
    type: "roost-example"
  ports:
  - name: election-commission
    port: 80
    targetPort: 80
    nodePort: 30031

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-commission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: election-commission
      type: "roost-example"
  template:
    metadata:
      labels:
        app: election-commission
        type: "roost-example"
    spec:
      containers:
      - name: election-commission
        image: zbio/election-commission:latest
        stdin: true
        tty: true
        env:
        - name: EC_SERVER_ENDPOINT
          value: roost-controlplane:30081
        ports:
        - containerPort: 80
---
