apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: election-commission
    type: roost-example
  name: {{ .Values.services.electionCommission.serviceName }}
spec: 
  type: NodePort
  selector: 
    app: election-commission
    type: roost-example
  ports:
  - name: http
    port: {{ .Values.httpServicePort }}
    targetPort: 80
    nodePort: 30031

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-commission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: election-commission
      type: roost-example
  template:
    metadata:
      labels:
        app: election-commission
        type: roost-example
    spec:
      containers:
      - name: election-commission
        image: {{ .Values.services.electionCommission.image }}
        stdin: true
        tty: true
        env:
        - name: EC_SERVER_ENDPOINT
          # value: roost-controlplane{{- .Values.services.ecserver.ingressEndpoint }}
          value: roost-controlplane:30081
        ports:
        - containerPort: 80
