apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: ecserver
  name: {{ .Values.services.ecserver.serviceName }}
spec: 
  selector: 
    app: ecserver
  ports:
  - name: http
    port: {{ .Values.httpServicePort }}
    targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecserver
  template:
    metadata:
      labels:
        app: ecserver
    spec:
      containers:
      - name: ecserver
        image: {{ .Values.services.ecserver.image }}
        ports:
        - containerPort: 8081
