apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: sample-test-suite
  name: sample-test-suite
spec: 
  type: NodePort
  selector: 
    app: sample-test-suite
  ports:
  - name: sample-test-suite
    port: 80
    targetPort: 5003
    nodePort: 30088

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballot-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-test-suite
  template:
    metadata:
      labels:
        app: sample-test-suite
    spec:
      containers:
      - name: ballot
        image: local-registry:5002/service-test-suite:latest
        ports:
        - containerPort: 5003
